package lab.processor;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.TypeElement;
import javax.tools.JavaFileObject;
import javax.tools.Diagnostic;
import java.io.PrintWriter;
import java.util.Set;

@SupportedAnnotationTypes("lab.anno.HelloAnnotation")
@SupportedSourceVersion(SourceVersion.RELEASE_11)
public class HelloAnnotationProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (TypeElement anno: annotations) {
            roundEnv.getElementsAnnotatedWith(anno).forEach(elem -> {
                try {
                    String name = elem.getAnnotation(lab.anno.HelloAnnotation.class).value();
                    System.out.println(elem.getKind());
                    String pkgName = ((TypeElement)elem).getQualifiedName().toString();
                    int lastDot = pkgName.lastIndexOf('.');
                    if (lastDot != -1) {
                        pkgName = pkgName.substring(0, lastDot);
                    } else {
                        pkgName = null;
                    }
                    String className = elem.getSimpleName() + "Generated";
                    JavaFileObject file = processingEnv.getFiler().createSourceFile(pkgName == null ? className : (pkgName + '.' + className));
                    try (PrintWriter writer = new PrintWriter(file.openWriter())) {
                        writer.println("// Auto-generated by HelloAnnotationProcessor");
                        if (pkgName != null) {
                            writer.println("package " + pkgName + ";");
                        }
                        writer.println("public class " + className + " {");
                        writer.println("    public static void sayHello() {");
                        writer.println("        System.out.println(\"Hello, " + name + "!\");");
                        writer.println("    }");
                        writer.println("}");
                    }
                } catch (Exception e) {
                    processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, e.getMessage());
                }
            });
        }
        return true;
    }
}
